//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:2.0.50727.3053
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This code was auto-generated by Microsoft.Silverlight.ServiceReference, version 3.0.40624.0
// 
namespace Database_fireworks_.ServiceReference1 {
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="table_signup1", Namespace="http://schemas.datacontract.org/2004/07/Database_fireworks_.Web")]
    public partial class table_signup1 : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Guid user_idField;
        
        private string first_nameField;
        
        private string last_nameField;
        
        private string user_nameField;
        
        private string addressField;
        
        private string date_of_birthField;
        
        private System.Nullable<int> genderField;
        
        private string passwordField;
        
        private string primary_emailField;
        
        private string alternate_emailField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Guid user_id {
            get {
                return this.user_idField;
            }
            set {
                if ((this.user_idField.Equals(value) != true)) {
                    this.user_idField = value;
                    this.RaisePropertyChanged("user_id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=1)]
        public string first_name {
            get {
                return this.first_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.first_nameField, value) != true)) {
                    this.first_nameField = value;
                    this.RaisePropertyChanged("first_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string last_name {
            get {
                return this.last_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.last_nameField, value) != true)) {
                    this.last_nameField = value;
                    this.RaisePropertyChanged("last_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string user_name {
            get {
                return this.user_nameField;
            }
            set {
                if ((object.ReferenceEquals(this.user_nameField, value) != true)) {
                    this.user_nameField = value;
                    this.RaisePropertyChanged("user_name");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=4)]
        public string address {
            get {
                return this.addressField;
            }
            set {
                if ((object.ReferenceEquals(this.addressField, value) != true)) {
                    this.addressField = value;
                    this.RaisePropertyChanged("address");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=5)]
        public string date_of_birth {
            get {
                return this.date_of_birthField;
            }
            set {
                if ((object.ReferenceEquals(this.date_of_birthField, value) != true)) {
                    this.date_of_birthField = value;
                    this.RaisePropertyChanged("date_of_birth");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=6)]
        public System.Nullable<int> gender {
            get {
                return this.genderField;
            }
            set {
                if ((this.genderField.Equals(value) != true)) {
                    this.genderField = value;
                    this.RaisePropertyChanged("gender");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=7)]
        public string password {
            get {
                return this.passwordField;
            }
            set {
                if ((object.ReferenceEquals(this.passwordField, value) != true)) {
                    this.passwordField = value;
                    this.RaisePropertyChanged("password");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=8)]
        public string primary_email {
            get {
                return this.primary_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.primary_emailField, value) != true)) {
                    this.primary_emailField = value;
                    this.RaisePropertyChanged("primary_email");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=9)]
        public string alternate_email {
            get {
                return this.alternate_emailField;
            }
            set {
                if ((object.ReferenceEquals(this.alternate_emailField, value) != true)) {
                    this.alternate_emailField = value;
                    this.RaisePropertyChanged("alternate_email");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "3.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="serverdb", Namespace="http://schemas.datacontract.org/2004/07/Database_fireworks_.Web")]
    public partial class serverdb : object, System.ComponentModel.INotifyPropertyChanged {
        
        private System.Nullable<System.Guid> uidField;
        
        private string usernameField;
        
        private string filenameField;
        
        private string richtextField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public System.Nullable<System.Guid> uid {
            get {
                return this.uidField;
            }
            set {
                if ((this.uidField.Equals(value) != true)) {
                    this.uidField = value;
                    this.RaisePropertyChanged("uid");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username {
            get {
                return this.usernameField;
            }
            set {
                if ((object.ReferenceEquals(this.usernameField, value) != true)) {
                    this.usernameField = value;
                    this.RaisePropertyChanged("username");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public string filename {
            get {
                return this.filenameField;
            }
            set {
                if ((object.ReferenceEquals(this.filenameField, value) != true)) {
                    this.filenameField = value;
                    this.RaisePropertyChanged("filename");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public string richtext {
            get {
                return this.richtextField;
            }
            set {
                if ((object.ReferenceEquals(this.richtextField, value) != true)) {
                    this.richtextField = value;
                    this.RaisePropertyChanged("richtext");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="", ConfigurationName="ServiceReference1.DemoService")]
    public interface DemoService {
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DemoService/GetRows", ReplyAction="urn:DemoService/GetRowsResponse")]
        System.IAsyncResult BeginGetRows(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> EndGetRows(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DemoService/GetRows1", ReplyAction="urn:DemoService/GetRows1Response")]
        System.IAsyncResult BeginGetRows1(System.AsyncCallback callback, object asyncState);
        
        System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> EndGetRows1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DemoService/InsertData", ReplyAction="urn:DemoService/InsertDataResponse")]
        System.IAsyncResult BeginInsertData(string sup_tbox_fname, string sup_tbox_lname, string sup_tbox_duname, string sup_tbox_add, int malefemale, string dob, string sup_pbox_pswd, string sup_tblox_pemail, string sup_tbox_aemail, System.AsyncCallback callback, object asyncState);
        
        void EndInsertData(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DemoService/InsertData1", ReplyAction="urn:DemoService/InsertData1Response")]
        System.IAsyncResult BeginInsertData1(string username, string filename, string richtext, System.AsyncCallback callback, object asyncState);
        
        void EndInsertData1(System.IAsyncResult result);
        
        [System.ServiceModel.OperationContractAttribute(AsyncPattern=true, Action="urn:DemoService/DeleteRow", ReplyAction="urn:DemoService/DeleteRowResponse")]
        System.IAsyncResult BeginDeleteRow(System.Guid uid, System.AsyncCallback callback, object asyncState);
        
        void EndDeleteRow(System.IAsyncResult result);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public interface DemoServiceChannel : Database_fireworks_.ServiceReference1.DemoService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetRowsCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRowsCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class GetRows1CompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        public GetRows1CompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        public System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> Result {
            get {
                base.RaiseExceptionIfNecessary();
                return ((System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb>)(this.results[0]));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "3.0.0.0")]
    public partial class DemoServiceClient : System.ServiceModel.ClientBase<Database_fireworks_.ServiceReference1.DemoService>, Database_fireworks_.ServiceReference1.DemoService {
        
        private BeginOperationDelegate onBeginGetRowsDelegate;
        
        private EndOperationDelegate onEndGetRowsDelegate;
        
        private System.Threading.SendOrPostCallback onGetRowsCompletedDelegate;
        
        private BeginOperationDelegate onBeginGetRows1Delegate;
        
        private EndOperationDelegate onEndGetRows1Delegate;
        
        private System.Threading.SendOrPostCallback onGetRows1CompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertDataDelegate;
        
        private EndOperationDelegate onEndInsertDataDelegate;
        
        private System.Threading.SendOrPostCallback onInsertDataCompletedDelegate;
        
        private BeginOperationDelegate onBeginInsertData1Delegate;
        
        private EndOperationDelegate onEndInsertData1Delegate;
        
        private System.Threading.SendOrPostCallback onInsertData1CompletedDelegate;
        
        private BeginOperationDelegate onBeginDeleteRowDelegate;
        
        private EndOperationDelegate onEndDeleteRowDelegate;
        
        private System.Threading.SendOrPostCallback onDeleteRowCompletedDelegate;
        
        private BeginOperationDelegate onBeginOpenDelegate;
        
        private EndOperationDelegate onEndOpenDelegate;
        
        private System.Threading.SendOrPostCallback onOpenCompletedDelegate;
        
        private BeginOperationDelegate onBeginCloseDelegate;
        
        private EndOperationDelegate onEndCloseDelegate;
        
        private System.Threading.SendOrPostCallback onCloseCompletedDelegate;
        
        public DemoServiceClient() {
        }
        
        public DemoServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DemoServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Net.CookieContainer CookieContainer {
            get {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    return httpCookieContainerManager.CookieContainer;
                }
                else {
                    return null;
                }
            }
            set {
                System.ServiceModel.Channels.IHttpCookieContainerManager httpCookieContainerManager = this.InnerChannel.GetProperty<System.ServiceModel.Channels.IHttpCookieContainerManager>();
                if ((httpCookieContainerManager != null)) {
                    httpCookieContainerManager.CookieContainer = value;
                }
                else {
                    throw new System.InvalidOperationException("Unable to set the CookieContainer. Please make sure the binding contains an HttpC" +
                            "ookieContainerBindingElement.");
                }
            }
        }
        
        public event System.EventHandler<GetRowsCompletedEventArgs> GetRowsCompleted;
        
        public event System.EventHandler<GetRows1CompletedEventArgs> GetRows1Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertDataCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> InsertData1Completed;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> DeleteRowCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> OpenCompleted;
        
        public event System.EventHandler<System.ComponentModel.AsyncCompletedEventArgs> CloseCompleted;
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Database_fireworks_.ServiceReference1.DemoService.BeginGetRows(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRows(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> Database_fireworks_.ServiceReference1.DemoService.EndGetRows(System.IAsyncResult result) {
            return base.Channel.EndGetRows(result);
        }
        
        private System.IAsyncResult OnBeginGetRows(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Database_fireworks_.ServiceReference1.DemoService)(this)).BeginGetRows(callback, asyncState);
        }
        
        private object[] OnEndGetRows(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> retVal = ((Database_fireworks_.ServiceReference1.DemoService)(this)).EndGetRows(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRowsCompleted(object state) {
            if ((this.GetRowsCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRowsCompleted(this, new GetRowsCompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRowsAsync() {
            this.GetRowsAsync(null);
        }
        
        public void GetRowsAsync(object userState) {
            if ((this.onBeginGetRowsDelegate == null)) {
                this.onBeginGetRowsDelegate = new BeginOperationDelegate(this.OnBeginGetRows);
            }
            if ((this.onEndGetRowsDelegate == null)) {
                this.onEndGetRowsDelegate = new EndOperationDelegate(this.OnEndGetRows);
            }
            if ((this.onGetRowsCompletedDelegate == null)) {
                this.onGetRowsCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRowsCompleted);
            }
            base.InvokeAsync(this.onBeginGetRowsDelegate, null, this.onEndGetRowsDelegate, this.onGetRowsCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Database_fireworks_.ServiceReference1.DemoService.BeginGetRows1(System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginGetRows1(callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> Database_fireworks_.ServiceReference1.DemoService.EndGetRows1(System.IAsyncResult result) {
            return base.Channel.EndGetRows1(result);
        }
        
        private System.IAsyncResult OnBeginGetRows1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((Database_fireworks_.ServiceReference1.DemoService)(this)).BeginGetRows1(callback, asyncState);
        }
        
        private object[] OnEndGetRows1(System.IAsyncResult result) {
            System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> retVal = ((Database_fireworks_.ServiceReference1.DemoService)(this)).EndGetRows1(result);
            return new object[] {
                    retVal};
        }
        
        private void OnGetRows1Completed(object state) {
            if ((this.GetRows1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.GetRows1Completed(this, new GetRows1CompletedEventArgs(e.Results, e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void GetRows1Async() {
            this.GetRows1Async(null);
        }
        
        public void GetRows1Async(object userState) {
            if ((this.onBeginGetRows1Delegate == null)) {
                this.onBeginGetRows1Delegate = new BeginOperationDelegate(this.OnBeginGetRows1);
            }
            if ((this.onEndGetRows1Delegate == null)) {
                this.onEndGetRows1Delegate = new EndOperationDelegate(this.OnEndGetRows1);
            }
            if ((this.onGetRows1CompletedDelegate == null)) {
                this.onGetRows1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnGetRows1Completed);
            }
            base.InvokeAsync(this.onBeginGetRows1Delegate, null, this.onEndGetRows1Delegate, this.onGetRows1CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Database_fireworks_.ServiceReference1.DemoService.BeginInsertData(string sup_tbox_fname, string sup_tbox_lname, string sup_tbox_duname, string sup_tbox_add, int malefemale, string dob, string sup_pbox_pswd, string sup_tblox_pemail, string sup_tbox_aemail, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertData(sup_tbox_fname, sup_tbox_lname, sup_tbox_duname, sup_tbox_add, malefemale, dob, sup_pbox_pswd, sup_tblox_pemail, sup_tbox_aemail, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Database_fireworks_.ServiceReference1.DemoService.EndInsertData(System.IAsyncResult result) {
            base.Channel.EndInsertData(result);
        }
        
        private System.IAsyncResult OnBeginInsertData(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string sup_tbox_fname = ((string)(inValues[0]));
            string sup_tbox_lname = ((string)(inValues[1]));
            string sup_tbox_duname = ((string)(inValues[2]));
            string sup_tbox_add = ((string)(inValues[3]));
            int malefemale = ((int)(inValues[4]));
            string dob = ((string)(inValues[5]));
            string sup_pbox_pswd = ((string)(inValues[6]));
            string sup_tblox_pemail = ((string)(inValues[7]));
            string sup_tbox_aemail = ((string)(inValues[8]));
            return ((Database_fireworks_.ServiceReference1.DemoService)(this)).BeginInsertData(sup_tbox_fname, sup_tbox_lname, sup_tbox_duname, sup_tbox_add, malefemale, dob, sup_pbox_pswd, sup_tblox_pemail, sup_tbox_aemail, callback, asyncState);
        }
        
        private object[] OnEndInsertData(System.IAsyncResult result) {
            ((Database_fireworks_.ServiceReference1.DemoService)(this)).EndInsertData(result);
            return null;
        }
        
        private void OnInsertDataCompleted(object state) {
            if ((this.InsertDataCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertDataCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertDataAsync(string sup_tbox_fname, string sup_tbox_lname, string sup_tbox_duname, string sup_tbox_add, int malefemale, string dob, string sup_pbox_pswd, string sup_tblox_pemail, string sup_tbox_aemail) {
            this.InsertDataAsync(sup_tbox_fname, sup_tbox_lname, sup_tbox_duname, sup_tbox_add, malefemale, dob, sup_pbox_pswd, sup_tblox_pemail, sup_tbox_aemail, null);
        }
        
        public void InsertDataAsync(string sup_tbox_fname, string sup_tbox_lname, string sup_tbox_duname, string sup_tbox_add, int malefemale, string dob, string sup_pbox_pswd, string sup_tblox_pemail, string sup_tbox_aemail, object userState) {
            if ((this.onBeginInsertDataDelegate == null)) {
                this.onBeginInsertDataDelegate = new BeginOperationDelegate(this.OnBeginInsertData);
            }
            if ((this.onEndInsertDataDelegate == null)) {
                this.onEndInsertDataDelegate = new EndOperationDelegate(this.OnEndInsertData);
            }
            if ((this.onInsertDataCompletedDelegate == null)) {
                this.onInsertDataCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertDataCompleted);
            }
            base.InvokeAsync(this.onBeginInsertDataDelegate, new object[] {
                        sup_tbox_fname,
                        sup_tbox_lname,
                        sup_tbox_duname,
                        sup_tbox_add,
                        malefemale,
                        dob,
                        sup_pbox_pswd,
                        sup_tblox_pemail,
                        sup_tbox_aemail}, this.onEndInsertDataDelegate, this.onInsertDataCompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Database_fireworks_.ServiceReference1.DemoService.BeginInsertData1(string username, string filename, string richtext, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginInsertData1(username, filename, richtext, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Database_fireworks_.ServiceReference1.DemoService.EndInsertData1(System.IAsyncResult result) {
            base.Channel.EndInsertData1(result);
        }
        
        private System.IAsyncResult OnBeginInsertData1(object[] inValues, System.AsyncCallback callback, object asyncState) {
            string username = ((string)(inValues[0]));
            string filename = ((string)(inValues[1]));
            string richtext = ((string)(inValues[2]));
            return ((Database_fireworks_.ServiceReference1.DemoService)(this)).BeginInsertData1(username, filename, richtext, callback, asyncState);
        }
        
        private object[] OnEndInsertData1(System.IAsyncResult result) {
            ((Database_fireworks_.ServiceReference1.DemoService)(this)).EndInsertData1(result);
            return null;
        }
        
        private void OnInsertData1Completed(object state) {
            if ((this.InsertData1Completed != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.InsertData1Completed(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void InsertData1Async(string username, string filename, string richtext) {
            this.InsertData1Async(username, filename, richtext, null);
        }
        
        public void InsertData1Async(string username, string filename, string richtext, object userState) {
            if ((this.onBeginInsertData1Delegate == null)) {
                this.onBeginInsertData1Delegate = new BeginOperationDelegate(this.OnBeginInsertData1);
            }
            if ((this.onEndInsertData1Delegate == null)) {
                this.onEndInsertData1Delegate = new EndOperationDelegate(this.OnEndInsertData1);
            }
            if ((this.onInsertData1CompletedDelegate == null)) {
                this.onInsertData1CompletedDelegate = new System.Threading.SendOrPostCallback(this.OnInsertData1Completed);
            }
            base.InvokeAsync(this.onBeginInsertData1Delegate, new object[] {
                        username,
                        filename,
                        richtext}, this.onEndInsertData1Delegate, this.onInsertData1CompletedDelegate, userState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.IAsyncResult Database_fireworks_.ServiceReference1.DemoService.BeginDeleteRow(System.Guid uid, System.AsyncCallback callback, object asyncState) {
            return base.Channel.BeginDeleteRow(uid, callback, asyncState);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        void Database_fireworks_.ServiceReference1.DemoService.EndDeleteRow(System.IAsyncResult result) {
            base.Channel.EndDeleteRow(result);
        }
        
        private System.IAsyncResult OnBeginDeleteRow(object[] inValues, System.AsyncCallback callback, object asyncState) {
            System.Guid uid = ((System.Guid)(inValues[0]));
            return ((Database_fireworks_.ServiceReference1.DemoService)(this)).BeginDeleteRow(uid, callback, asyncState);
        }
        
        private object[] OnEndDeleteRow(System.IAsyncResult result) {
            ((Database_fireworks_.ServiceReference1.DemoService)(this)).EndDeleteRow(result);
            return null;
        }
        
        private void OnDeleteRowCompleted(object state) {
            if ((this.DeleteRowCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.DeleteRowCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void DeleteRowAsync(System.Guid uid) {
            this.DeleteRowAsync(uid, null);
        }
        
        public void DeleteRowAsync(System.Guid uid, object userState) {
            if ((this.onBeginDeleteRowDelegate == null)) {
                this.onBeginDeleteRowDelegate = new BeginOperationDelegate(this.OnBeginDeleteRow);
            }
            if ((this.onEndDeleteRowDelegate == null)) {
                this.onEndDeleteRowDelegate = new EndOperationDelegate(this.OnEndDeleteRow);
            }
            if ((this.onDeleteRowCompletedDelegate == null)) {
                this.onDeleteRowCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnDeleteRowCompleted);
            }
            base.InvokeAsync(this.onBeginDeleteRowDelegate, new object[] {
                        uid}, this.onEndDeleteRowDelegate, this.onDeleteRowCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginOpen(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(callback, asyncState);
        }
        
        private object[] OnEndOpen(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndOpen(result);
            return null;
        }
        
        private void OnOpenCompleted(object state) {
            if ((this.OpenCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.OpenCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void OpenAsync() {
            this.OpenAsync(null);
        }
        
        public void OpenAsync(object userState) {
            if ((this.onBeginOpenDelegate == null)) {
                this.onBeginOpenDelegate = new BeginOperationDelegate(this.OnBeginOpen);
            }
            if ((this.onEndOpenDelegate == null)) {
                this.onEndOpenDelegate = new EndOperationDelegate(this.OnEndOpen);
            }
            if ((this.onOpenCompletedDelegate == null)) {
                this.onOpenCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnOpenCompleted);
            }
            base.InvokeAsync(this.onBeginOpenDelegate, null, this.onEndOpenDelegate, this.onOpenCompletedDelegate, userState);
        }
        
        private System.IAsyncResult OnBeginClose(object[] inValues, System.AsyncCallback callback, object asyncState) {
            return ((System.ServiceModel.ICommunicationObject)(this)).BeginClose(callback, asyncState);
        }
        
        private object[] OnEndClose(System.IAsyncResult result) {
            ((System.ServiceModel.ICommunicationObject)(this)).EndClose(result);
            return null;
        }
        
        private void OnCloseCompleted(object state) {
            if ((this.CloseCompleted != null)) {
                InvokeAsyncCompletedEventArgs e = ((InvokeAsyncCompletedEventArgs)(state));
                this.CloseCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(e.Error, e.Cancelled, e.UserState));
            }
        }
        
        public void CloseAsync() {
            this.CloseAsync(null);
        }
        
        public void CloseAsync(object userState) {
            if ((this.onBeginCloseDelegate == null)) {
                this.onBeginCloseDelegate = new BeginOperationDelegate(this.OnBeginClose);
            }
            if ((this.onEndCloseDelegate == null)) {
                this.onEndCloseDelegate = new EndOperationDelegate(this.OnEndClose);
            }
            if ((this.onCloseCompletedDelegate == null)) {
                this.onCloseCompletedDelegate = new System.Threading.SendOrPostCallback(this.OnCloseCompleted);
            }
            base.InvokeAsync(this.onBeginCloseDelegate, null, this.onEndCloseDelegate, this.onCloseCompletedDelegate, userState);
        }
        
        protected override Database_fireworks_.ServiceReference1.DemoService CreateChannel() {
            return new DemoServiceClientChannel(this);
        }
        
        private class DemoServiceClientChannel : ChannelBase<Database_fireworks_.ServiceReference1.DemoService>, Database_fireworks_.ServiceReference1.DemoService {
            
            public DemoServiceClientChannel(System.ServiceModel.ClientBase<Database_fireworks_.ServiceReference1.DemoService> client) : 
                    base(client) {
            }
            
            public System.IAsyncResult BeginGetRows(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRows", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> EndGetRows(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1> _result = ((System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.table_signup1>)(base.EndInvoke("GetRows", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginGetRows1(System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[0];
                System.IAsyncResult _result = base.BeginInvoke("GetRows1", _args, callback, asyncState);
                return _result;
            }
            
            public System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> EndGetRows1(System.IAsyncResult result) {
                object[] _args = new object[0];
                System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb> _result = ((System.Collections.ObjectModel.ObservableCollection<Database_fireworks_.ServiceReference1.serverdb>)(base.EndInvoke("GetRows1", _args, result)));
                return _result;
            }
            
            public System.IAsyncResult BeginInsertData(string sup_tbox_fname, string sup_tbox_lname, string sup_tbox_duname, string sup_tbox_add, int malefemale, string dob, string sup_pbox_pswd, string sup_tblox_pemail, string sup_tbox_aemail, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[9];
                _args[0] = sup_tbox_fname;
                _args[1] = sup_tbox_lname;
                _args[2] = sup_tbox_duname;
                _args[3] = sup_tbox_add;
                _args[4] = malefemale;
                _args[5] = dob;
                _args[6] = sup_pbox_pswd;
                _args[7] = sup_tblox_pemail;
                _args[8] = sup_tbox_aemail;
                System.IAsyncResult _result = base.BeginInvoke("InsertData", _args, callback, asyncState);
                return _result;
            }
            
            public void EndInsertData(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("InsertData", _args, result);
            }
            
            public System.IAsyncResult BeginInsertData1(string username, string filename, string richtext, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[3];
                _args[0] = username;
                _args[1] = filename;
                _args[2] = richtext;
                System.IAsyncResult _result = base.BeginInvoke("InsertData1", _args, callback, asyncState);
                return _result;
            }
            
            public void EndInsertData1(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("InsertData1", _args, result);
            }
            
            public System.IAsyncResult BeginDeleteRow(System.Guid uid, System.AsyncCallback callback, object asyncState) {
                object[] _args = new object[1];
                _args[0] = uid;
                System.IAsyncResult _result = base.BeginInvoke("DeleteRow", _args, callback, asyncState);
                return _result;
            }
            
            public void EndDeleteRow(System.IAsyncResult result) {
                object[] _args = new object[0];
                base.EndInvoke("DeleteRow", _args, result);
            }
        }
    }
}
