<?xml version="1.0" encoding="utf-8"?>
<Database Name="NORTHWND" Class="DataClasses1DataContext" Serialization="Unidirectional" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=.\SQLEXPRESS;AttachDbFilename=|DataDirectory|\NORTHWND.MDF;Integrated Security=True;User Instance=True" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="NORTHWNDConnectionString1" Provider="System.Data.SqlClient" />
  <Table Name="dbo.serverdb" Member="serverdbs">
    <Type Name="serverdb">
      <Column Name="uid" Type="System.Guid" DbType="UniqueIdentifier" IsPrimaryKey="true" CanBeNull="true" />
      <Column Name="username" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="filename" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="richtext" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
  <Table Name="dbo.table_signup1" Member="table_signup1s">
    <Type Name="table_signup1">
      <Column Name="user_id" Type="System.Guid" DbType="UniqueIdentifier NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="first_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="last_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="user_name" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="address" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="date_of_birth" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
      <Column Name="gender" Type="System.Int32" DbType="Int" CanBeNull="true" />
      <Column Name="password" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="primary_email" Type="System.String" DbType="Text NOT NULL" CanBeNull="false" UpdateCheck="Never" />
      <Column Name="alternate_email" Type="System.String" DbType="Text" CanBeNull="true" UpdateCheck="Never" />
    </Type>
  </Table>
</Database>